# Generated by Django 2.1.7 on 2019-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('publishTime', models.CharField(max_length=15)),
                ('repost', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('address', models.CharField(max_length=150)),
            ],
        ),
    ]
