# Generated by Django 2.1.7 on 2019-05-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='address',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='content',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotspot',
            name='publishTime',
            field=models.CharField(max_length=255),
        ),
    ]
