# Generated by Django 2.1.7 on 2019-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20190502_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreshNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishTime', models.CharField(max_length=255)),
                ('address', models.URLField()),
                ('image', models.URLField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='hotspot',
            options={'ordering': ['-id']},
        ),
    ]
