# Generated by Django 2.1.7 on 2019-05-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0003_auto_20190506_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotspot',
            name='image',
            field=models.URLField(default='https://wx2.sinaimg.cn/crop.28.0.457.343.240/005v4nJEly1g2rlnbru7sj30ea09jwl0.jpg'),
        ),
    ]
