# Generated by Django 2.1.7 on 2019-05-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0004_hotspot_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishTime', models.CharField(max_length=255)),
                ('repost', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('address', models.URLField()),
                ('image', models.URLField(default='https://wx4.sinaimg.cn/thumb150/9b6feba7ly1g35vpfaml8j222o340b2b.jpg')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FunnyStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishTime', models.CharField(max_length=255)),
                ('repost', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('address', models.URLField()),
                ('image', models.URLField(default='https://wx1.sinaimg.cn/thumb150/9b6feba7ly1g2qtanp6igj21l62dse07.jpg')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishTime', models.CharField(max_length=255)),
                ('repost', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('address', models.URLField()),
                ('image', models.URLField(default='https://wx2.sinaimg.cn/thumb150/9b6feba7ly1g2kjezpysej22c03401kz.jpg')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='TopEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishTime', models.CharField(max_length=255)),
                ('repost', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('address', models.URLField()),
                ('image', models.URLField(default='https://wx1.sinaimg.cn/thumb150/9b6feba7ly1g37xa50pf8j222o340npe.jpg')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
