# Generated by Django 2.1.7 on 2019-05-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0005_fashion_funnystory_society_topevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publishTime', models.CharField(max_length=255)),
                ('repost', models.IntegerField()),
                ('comment', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('address', models.URLField()),
                ('image', models.URLField(default='https://wx1.sinaimg.cn/thumb150/9b6feba7ly1g37xa50pf8j222o340npe.jpg')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
